name: Deploy to NPM

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npx vitest run
        
      - name: Compile Code
        run: npm run build
        
      - name: Release with Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
